config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  get '/admin/users/export', to: 'admin/users#export', as: :admin_users_export
  # for showing deleted data
  get '/admin/posts/deleted_record', to: 'admin/posts#deleted_record', as: :admin_posts_deleted_record
  # for deleteing permanently the post data
  delete '/admin/posts/destroy_data', to: 'admin/posts#destroy_data', as: :admin_posts_destroy_data
  # for undoing post
  get '/admin/posts/restore', to: 'admin/posts#restore', as: :admin_posts_restore
  # for saving versiions in paper trail
  post '/admin/posts/paper_update', to: 'admin/posts#paper_update', as: :admin_posts_paper_update

  # for users
  # for showing deleted data
  get '/admin/users/deleted_record', to: 'admin/users#deleted_record', as: :admin_users_deleted_record
  ActiveAdmin.routes(self)

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  # authenticate :user, lambda { |u| u.admin? } do
  #   mount Sidekiq::Web => '/sidekiq'
  # end
  # get 'admin/post/history', to: 'admin/posts#history', as: :admin_post_history
  # post 'versions/:id/revert', to: 'versions#revert'
end

app/models/admin_user.rb
# frozen_string_literal: true

class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable

  def name
    email
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/myfile.rb
# frozen_string_literal: true

class Myfile < ApplicationRecord
  include ImageUploader::Attachment(:image)
  validates :title, presence: true
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  has_paper_trail

  acts_as_paranoid

  # has_paper_trail :if     => Proc.new { |t| t.language_code == 'US' },
  #                 :unless => Proc.new { |t| t.type == 'DRAFT'       }

  belongs_to :user
  # attr_accessible: :name, :gender
  #     before_validation :set_user

  # private
  #   def set_user
  #   @user = User.find_or_create_by(email: self.user_id)
  #   @user.save
  #   end

  # def self.drop_down_options
  #     User.all.map { |p| [p.use, p.id] }
  # end

  # def use
  #     "#{user.username}"
  # end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  acts_as_paranoid

  has_paper_trail
  def self.to_csv(errors)
    CSV.generate do |csv|
      csv << %w[row username phone description error]
      errors.each do |error|
        # error.delete('row')
        # error.delete('error')
        csv << error.values
      end
    end
  end
  # has_one_attached :csv
  has_many :posts
  validates :username, presence: true, uniqueness: { case_sensitive: false }

  def name
    username
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :set_paper_trail_whodunnit
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def user_for_paper_trail
    admin_user_signed_in? ? current_admin_user.try(:id) : 'Unknown user'
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_in) do |user_params|
      user_params.permit(:username, :email, :phone)
    end
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/admin/users/user_import.html.erb
<h1>Errors List</h1>

<table style="border: solid 2px lightgrey;">
  <tr>
    <th style="font-size:20px;">Row Number</th>              
    <th style="font-size:20px;">Username </th>                      
    <th style="font-size:20px;">Phone</th>
    <th style="color:black;font-size:20px;" >Errors (Please Fix These Errors)</th>
  </tr>
 
 <% @errors.each do |error| %>
  
 
    <tr>
    <td style="font-size:15px;" ><%=error["row"]%></td>       
    <td style="font-size:15px;" ><%=error["username"]%></td>  
    <td style="font-size:15px;" ><%=error["phone"] %></td>   
    <td style="color:red;font-size:18px;" ><%=error["error"] {:style=>"color: red;"} %></td>
    </tr>
  <% end %>
 </table>

<h3 style="color:red;" >Click below link to download records that were unable to import. Please edit and import it again!!</h3>
<div style="font-size:20px;">
<%= link_to "Download CSV", admin_users_export_path(:errors => @errors, :format => "csv" ) %>
</div>

app/views/admin_users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin_users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/layouts/_version.html.erb
<% if !@versions.empty? %>
  <h3>Current Version: <%= @versions.length %></h3>

  <b>Created At:</b>
  <%= @versions.last.created_at%>
  <br>
  <b>Admin</b>: <%= AdminUser.find(@versions.last.whodunnit).email %>
  <br>
  <% if @versions.length.to_i > 1 %>
    <% if params[:version].to_i > 1 || !params[:version] %>

    <button style='background: #0069d9;'>
      <%= link_to "Previous version", {:version => (params[:version] || @versions.length).to_i - 1}, style: "color: #FFFFFF; text-decoration: none;"%>

      <%= link_to "Previous version", {:version => (params[:version] || @versions.length).to_i - 1}%>

      <br>
    <% end %>
    <% if params[:version] %>
      <h3>This is <%= "#{params[:version]}"%> version</h3>

      <b>Modify at:</b>
      <%= @versions[(params[:version].to_i - 1)].created_at %>
      <br>
      <b>Admin</b>:
      <%= AdminUser.find(@versions[(params[:version].to_i - 1)].whodunnit).email %>
      <br>


      <button style='background: #356b76;'>

      <%= link_to "Go to current version",{}, style: "color: white; text-decoration: none;" %>
      </button>

      <div style='float: right;'>
     <button style='background: green;'>
      <%= link_to "Save",admin_posts_paper_update_path({:version => (params[:version] || @versions.length).to_i }),method: :post, style: "color: white; text-decoration: none;"%>
      </button>
      </div>
      <% end %>
      <% end %>
      <% else %>
      <p>This item does not have any registered version.</p>

      <%= link_to "Go to current version"%>
    <% end %>
  <% end %>
<% else %>
  <p>This item does not have any registered version.</p>

<% end %>

app/views/layouts/_versionuse.html.erb
<% if !@versions.empty? %>
  <h3>Current Version: <%= @versions.length %></h3>

  <b>Created At:</b>
  <%= @versions.last.created_at%>
  <br>
  <b>Admin</b>: <%= AdminUser.find(@versions.last.whodunnit).email %>
  <br>
  <% if @versions.length.to_i > 1 %>
    <% if params[:version].to_i > 1 || !params[:version] %>

      <button style='background: #0069d9;'>
      <%= link_to "Previous version", {:version => (params[:version] || @versions.length).to_i - 1}, style: "color: #FFFFFF; text-decoration: none;"%>

      </button>

      <br>
    <% end %>
    <% if params[:version] %>
      <h3>This is <%= "#{params[:version]}"%> version</h3>

      <b>Modify at:</b>
      <%= @versions[(params[:version].to_i - 1)].created_at %>
      <br>
      <b>Admin</b>:
      <%= AdminUser.find(@versions[(params[:version].to_i - 1)].whodunnit).email %>
      <br>
      <button style='background: #356b76;'>
      <%= link_to "Go to current version",{}, style: "color: white; text-decoration: none;" %>
      </button>
      <div style='float: right;'>
     <button style='background: green;'>
      <%= link_to "Save",admin_users_paper_update_path({:version => (params[:version] || @versions.length).to_i }),method: :post, style: "color: white; text-decoration: none;"%>
      </button>
      </div>
      <% end %>
  <% end %>
<% else %>
  <p>This item does not have any registered version.</p>

<% end %>